import { Router } from 'express';
import { z } from 'zod';
import { authenticate } from '../middleware/auth';
import { asyncHandler, HttpError } from '../middleware/errorHandler';
import { assertDemandEditable, assertDemandWeeksEditable } from '../middleware/recordAccess';
import { demandRepository } from '../repositories/sql';
import { decodeArray } from '../utils/arrayParser';

const router = Router();
const createSchema = z.object({ projectId: z.string().min(1), personId: z.string().min(1).optional(), functionId: z.string().min(1).optional(), name: z.string().max(200).optional(), status: z.string().max(100).optional(), isActive: z.boolean().optional(), startWeek: z.number().int().min(0).max(1332).optional(), endWeek: z.number().int().min(0).max(1332).optional(), hoursPerWeek: z.number().int().min(0).max(99).optional(), weeks: z.array(z.number().int().min(0).max(99)).max(1333).optional() });
const weekUpdateSchema = z.object({ week: z.number().int().min(0).max(1332).optional(), startWeek: z.number().int().min(0).max(1332).optional(), endWeek: z.number().int().min(0).max(1332).optional(), hours: z.number().int().min(0).max(99) });
function toDemand(record: Awaited<ReturnType<typeof demandRepository.findByIdentifier>>) { if (!record) throw new HttpError(404, 'Demand record not found.'); return { id: record.DemandApiId, name: record.Name, projectId: record.ProjectApiId, projectName: record.ProjectName, personId: record.PersonApiId ?? undefined, personName: record.PersonName ?? undefined, functionId: record.FunctionApiId ?? undefined, functionName: record.FunctionName ?? undefined, demandHours: record.DemandHours, weeks: record.Weeks, startWeek: record.StartWeek, endWeek: record.EndWeek, status: record.StatusCode, isActive: record.IsActive }; }
router.use(authenticate);
router.get('/', asyncHandler(async (req, res) => { if (req.query.mine === 'true' && !req.user?.personId) throw new HttpError(400, 'No person record is linked to your account.'); const rows = await demandRepository.list({ includeInactive: true, projectId: req.query.projectId ? String(req.query.projectId) : undefined, personId: req.query.mine === 'true' ? req.user?.personId : req.query.personId ? String(req.query.personId) : undefined }); res.json(rows.map(toDemand)); }));
router.get('/:id', asyncHandler(async (req, res) => res.json(toDemand(await demandRepository.findByIdentifier(req.params.id)))));
router.post('/', asyncHandler(async (req, res) => { const input = createSchema.parse(req.body); const assigningSelf = Boolean(input.personId && req.user?.personId && input.personId.toLowerCase() === req.user.personId.toLowerCase()); if (!assigningSelf) await assertDemandEditable(req.user, input.projectId); const projectId = await demandRepository.resolveId('Projects', 'ProjectId', input.projectId); if (!projectId) throw new HttpError(404, 'Project not found.'); const personId = input.personId ? await demandRepository.resolveId('People', 'PersonId', input.personId) : null; const functionId = input.functionId ? await demandRepository.resolveId('Functions', 'FunctionId', input.functionId) : null; if (personId && await demandRepository.findByProjectAndPerson(input.projectId, input.personId!)) throw new HttpError(409, 'That person is already on this project team.'); let weeks = input.weeks ?? []; if (!input.weeks && input.startWeek !== undefined && input.endWeek !== undefined && input.hoursPerWeek !== undefined) { if (input.endWeek < input.startWeek) throw new HttpError(400, 'endWeek must be on or after startWeek.'); weeks = new Array(1333).fill(0); for (let i = input.startWeek; i <= input.endWeek; i += 1) weeks[i] = input.hoursPerWeek; } const id = await demandRepository.create({ ProjectId: projectId, PersonId: personId, FunctionId: functionId, Name: input.name, StatusCode: input.status ?? 'Planned' }, weeks, input.startWeek, input.endWeek); const created = await demandRepository.findByIdentifier(String(id)); res.status(201).json({ id: toDemand(created).id }); }));
router.patch('/:id/weeks', asyncHandler(async (req, res) => { await assertDemandWeeksEditable(req.user, req.params.id); const input = weekUpdateSchema.parse(req.body); const current = await demandRepository.findByIdentifier(req.params.id); if (!current) throw new HttpError(404, 'Demand record not found.'); const updated = input.week !== undefined ? await demandRepository.setWeek(current.DemandAllocationId, input.week, input.hours) : input.startWeek !== undefined && input.endWeek !== undefined ? await demandRepository.setRange(current.DemandAllocationId, input.startWeek, input.endWeek, input.hours) : null; if (!updated) throw new HttpError(400, 'Provide either week or startWeek/endWeek.'); res.json({ id: req.params.id, weeks: decodeArray(updated.DemandHours) }); }));
router.patch('/:id', asyncHandler(async (req, res) => { const current = await demandRepository.findByIdentifier(req.params.id); if (!current) throw new HttpError(404, 'Demand record not found.'); await assertDemandEditable(req.user, current.ProjectApiId); const input = createSchema.partial().parse(req.body); const personId = input.personId ? await demandRepository.resolveId('People', 'PersonId', input.personId) : undefined; const functionId = input.functionId ? await demandRepository.resolveId('Functions', 'FunctionId', input.functionId) : undefined; await demandRepository.update(current.DemandAllocationId, { PersonId: personId, FunctionId: functionId, Name: input.name, StatusCode: input.status, ProjectId: input.projectId ? await demandRepository.resolveId('Projects', 'ProjectId', input.projectId) ?? undefined : undefined }, input.weeks, input.startWeek, input.endWeek); if (input.isActive === false) await demandRepository.deactivate(current.DemandAllocationId); res.json({ id: req.params.id }); }));
router.delete('/:id', asyncHandler(async (req, res) => { const current = await demandRepository.findByIdentifier(req.params.id); if (!current) throw new HttpError(404, 'Demand record not found.'); await assertDemandEditable(req.user, current.ProjectApiId); await demandRepository.deactivate(current.DemandAllocationId); res.status(204).end(); }));
export default router;
