/**
 * Column maps for the linked Dataverse tables.
 *
 * Logical column names follow the publisher prefix of each table (`new_` / `cr714_`).
 * Run `GET /api/metadata/:table` to list the real attributes in the MBO-Staffing-Model
 * environment and adjust any entry here that does not match.
 */
export const COLUMNS = {
  people: {
    id: 'new_peopleid',
    name: 'new_name',
    email: 'new_email',
    userId: '_new_user_value',
    userBind: 'new_User',
    departmentId: '_new_department_value',
    departmentBind: 'new_Department',
    functionId: '_new_function_value',
    functionBind: 'new_Function',
    siteId: '_new_site_value',
    siteBind: 'new_Site',
    skillsetId: '_new_skillset_value',
    skillsetBind: 'new_Skillset',
    role: 'new_role',
    title: 'new_title',
    employmentType: 'new_employmenttype',
    ftePercent: 'new_ftepercent',
    weeklyHours: 'new_weeklyhours',
    isActive: 'new_isactive',
  },
  departments: {
    id: 'new_departmentid',
    name: 'new_name',
    code: 'new_code',
    leadPersonId: '_new_lead_value',
    leadBind: 'new_Lead',
    delegatePersonId: '_new_delegate_value',
    delegateBind: 'new_Delegate',
    functionId: '_new_function_value',
    functionBind: 'new_Function',
    lastCheckIn: 'new_lastcheckin',
    isActive: 'new_isactive',
  },
  functions: {
    id: 'new_functionsid',
    name: 'new_name',
    code: 'new_code',
    departmentId: '_new_department_value',
    departmentBind: 'new_Department',
  },
  projects: {
    id: 'new_projectsid',
    name: 'new_name',
    code: 'new_code',
    spotId: 'new_spotid',
    description: 'new_description',
    problemStatement: 'new_problemstatement',
    status: 'new_status',
    started: 'new_started',
    priorityScore: 'new_priorityscore',
    startDate: 'new_startdate',
    endDate: 'new_enddate',
    managerPersonId: '_new_projectmanager_value',
    managerBind: 'new_ProjectManager',
    sponsorPersonId: '_new_sponsor_value',
    sponsorBind: 'new_Sponsor',
    delegatePersonId: '_new_delegate_value',
    delegateBind: 'new_Delegate',
    isActive: 'new_isactive',
    lastCheckIn: 'new_lastcheckin',
    programId: '_new_program_value',
    programBind: 'new_Program',
    departmentId: '_new_department_value',
    departmentBind: 'new_Department',
    requestId: '_new_request_value',
    requestBind: 'new_Request',
  },
  requests: {
    id: 'cr714_requestsid',
    name: 'cr714_name',
    title: 'cr714_title',
    shortTitle: 'cr714_shorttitle',
    spotId: 'cr714_spotid',
    phase: 'cr714_phase',
    problemStatement: 'cr714_problemstatement',
    businessCase: 'cr714_businesscase',
    expectedBenefit: 'cr714_expectedbenefit',
    status: 'cr714_status',
    submittedOn: 'cr714_submittedon',
    requesterPersonId: '_cr714_requester_value',
    requesterBind: 'cr714_Requester',
    delegatePersonId: '_cr714_delegate_value',
    delegateBind: 'cr714_Delegate',
    isActive: 'cr714_isactive',
    departmentId: '_cr714_department_value',
    departmentBind: 'cr714_Department',
    categoryId: '_cr714_category_value',
    categoryBind: 'cr714_Category',
    priorityScore: 'cr714_priorityscore',
    projectId: '_cr714_project_value',
    projectBind: 'cr714_Project',
  },
  demand: {
    id: 'new_demandid',
    name: 'new_name',
    projectId: '_new_project_value',
    projectBind: 'new_Project',
    personId: '_new_person_value',
    personBind: 'new_Person',
    functionId: '_new_function_value',
    functionBind: 'new_Function',
    hoursArray: 'new_demandhours',
    startWeek: 'new_startweek',
    endWeek: 'new_endweek',
    status: 'new_status',
    isActive: 'new_isactive',
  },
  capacity: {
    id: 'new_capacityid',
    name: 'new_name',
    personId: '_new_person_value',
    personBind: 'new_Person',
    departmentId: '_new_department_value',
    departmentBind: 'new_Department',
    hoursArray: 'new_availabilityhours',
    weeklyBaseline: 'new_weeklybaseline',
    notes: 'new_notes',
    isActive: 'new_isactive',
  },
  questions: {
    id: 'cr714_questionsid',
    name: 'cr714_name',
    text: 'cr714_questiontext',
    categoryId: '_cr714_category_value',
    categoryBind: 'cr714_Category',
    weight: 'cr714_weight',
    sequence: 'cr714_sequence',
    answerType: 'cr714_answertype',
    isActive: 'cr714_isactive',
  },
  answers: {
    id: 'cr714_answersid',
    name: 'cr714_name',
    questionId: '_cr714_question_value',
    questionBind: 'cr714_Question',
    requestId: '_cr714_request_value',
    requestBind: 'cr714_Request',
    value: 'cr714_value',
    score: 'cr714_score',
    comment: 'cr714_comment',
  },
  categories: {
    id: 'cr714_categoriesid',
    name: 'cr714_name',
    weight: 'cr714_weight',
  },
  programs: { id: 'cr714_programsid', name: 'cr714_name' },
  locations: { id: 'cr714_locationsid', name: 'cr714_name' },
  sites: { id: 'new_sitesid', name: 'new_name' },
  skillsets: { id: 'new_skillsetsid', name: 'new_name' },
  adm: { id: 'new_admid', name: 'new_name' },
  feedback: {
    id: 'cr714_feedbackid',
    name: 'cr714_name',
    comment: 'cr714_comment',
    rating: 'cr714_rating',
    projectId: '_cr714_project_value',
    projectBind: 'cr714_Project',
  },
  users: {
    id: 'systemuserid',
    fullName: 'fullname',
    email: 'internalemailaddress',
    domainName: 'domainname',
    jobTitle: 'title',
    isDisabled: 'isdisabled',
    businessUnitId: '_businessunitid_value',
  },
} as const;

/** Formatted (display) value annotation emitted by Dataverse for lookups and choices. */
export const FORMATTED = '@OData.Community.Display.V1.FormattedValue';

export function formatted(record: Record<string, unknown>, column: string): string | undefined {
  return record[`${column}${FORMATTED}`] as string | undefined;
}
